//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dirkj.hafas.net
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.7.2558.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class JourneyDetail
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stop")]
        public Stop[] Stop;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JourneyName")]
        public JourneyName[] JourneyName;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JourneyType")]
        public JourneyType[] JourneyType;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Note")]
        public Note[] Note;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable = false)]
        public JourneyDetailMessage[] MessageList;

        /// <remarks/>
        public JourneyDetailJourneyChange JourneyChange;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Stop
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdx;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string x;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string y;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string depTime;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string depDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arrTime;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arrDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string track;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtDepTime;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtDepDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtArrTime;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtArrDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtTrack;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class JourneyName
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxFrom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxTo;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class JourneyType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public JourneyTypeType type;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxFrom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxTo;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum JourneyTypeType
    {

        /// <remarks/>
        IC,

        /// <remarks/>
        LYN,

        /// <remarks/>
        REG,

        /// <remarks/>
        S,

        /// <remarks/>
        TOG,

        /// <remarks/>
        BUS,

        /// <remarks/>
        EXB,

        /// <remarks/>
        NB,

        /// <remarks/>
        TB,

        /// <remarks/>
        F,

        /// <remarks/>
        M,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Note
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxFrom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxTo;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JourneyDetailMessage
    {

        /// <remarks/>
        public string Header;

        /// <remarks/>
        public string Text;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Link", IsNullable = false)]
        public JourneyDetailMessageLink[] Links;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JourneyDetailMessageLink
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JourneyDetailJourneyChange
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxFrom;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string routeIdxTo;
    }
}